debug = true

[fastapi]
host = "0.0.0.0"
port = 8080

[github]
client_id = ""
client_secret = ""
redirect_uri = ""

[mysql]
host = ""
user = ""
password = ""
db = ""
autocommit = true

[frontend]
url = ""